const nome = prompt('digite seu nome completo')
document.body.innerHTML += `Seu nome é ${nome} <br />`;
document.body.innerHTML += `Seu nome tem ${nome.length}  <br />`;
document.body.innerHTML += `A segunda letra do seu nome é: ${nome.charAt(1)} <br />`;
document.body.innerHTML += `Qual e o primeiro indice da letra A seu nome: ${nome.indexOf('a')}   <br />`;
document.body.innerHTML += `Qual e o primeiro indice da letra A seu nome: ${nome.lastIndexOf('a')}   <br />`;
document.body.innerHTML += `As ultimas 3 letras do seu nome sao ${nome.slice(-3)} <br />`;
document.body.innerHTML += `As palavras do seu nome sao ${nome.split(' ')} <br />`;
document.body.innerHTML += `Seu nome com letras maiusculas  ${nome.toUpperCase()} <br />`;
document.body.innerHTML += `Seu nome com letras minusculas   ${nome.toLowerCase()}  <br />`;